# This file contains information which is proprietary to Riverlane Limited
# ("Riverlane") and is Riverlane Confidential Information.
# (c) Copyright Riverlane 2025-2026. All rights reserved.

"""Implementation of the :class:`.LocatedObservableToMove` pass.

This pass implements the minimum needed for a memory-like experiment to be generated by the patch
lowering pipeline. In particular, it assumes that the observable never moves (which makes the
problem trivial: just remove all the ``sobs.locate_observable``, as if the observable never moves,
they all re-define the observable on the same qubits as the initial ``sobs.dec_observable``
operation).

Later, this pass will need to find the stabilisers that can be used in order to move the observable
from one place to the other.
"""

from dataclasses import dataclass

from typing_extensions import override
from xdsl.dialects import builtin
from xdsl.dialects.builtin import ModuleOp
from xdsl.passes import ModulePass
from xdsl.pattern_rewriter import (
    GreedyRewritePatternApplier,
    PatternRewriter,
    PatternRewriteWalker,
    RewritePattern,
    op_type_rewrite_pattern,
)
from xdsl.transforms.reconcile_unrealized_casts import ReconcileUnrealizedCastsPattern

from deltakit_compile.dialects import sobs


@dataclass
class _LocateObservablePattern(RewritePattern):
    """Translates a ``sobs.locate_observable`` into a trivial ``builtin.unrealized_conversion_cast``
    that can be canonicalised out."""

    @override
    @op_type_rewrite_pattern
    def match_and_rewrite(self, op: sobs.LocateObservableOp, rewriter: PatternRewriter) -> None:
        unrealised_cast_op, new_result = builtin.UnrealizedConversionCastOp.cast_one(
            op.obs, sobs.ObservableType()
        )
        rewriter.replace_op(op, unrealised_cast_op, (new_result,))


@dataclass(frozen=True)
class LocatedObservableToMove(ModulePass):
    """Remove ``sobs.locate_observable`` under the assumption that observables do not move.

    This is currently a minimum viable implementation for memory-like experiments where the
    observable does not have to move. It will be improved later to include moving observables.
    """

    name = "located-observable-to-move"

    @override
    def apply(self, ctx, op: ModuleOp) -> None:
        PatternRewriteWalker(
            GreedyRewritePatternApplier([_LocateObservablePattern()])
        ).rewrite_module(op)
        PatternRewriteWalker(ReconcileUnrealizedCastsPattern()).rewrite_module(op)
