from pathlib import Path

DELTAKIT_COMPILE_TEST_FOLDER = Path(__file__).parent.parent
DELTAKIT_COMPILE_FOLDER = DELTAKIT_COMPILE_TEST_FOLDER.parent
DELTAKIT_COMPILE_TEST_RESOURCES_FOLDER = DELTAKIT_COMPILE_TEST_FOLDER / "resources"
DELTAKIT_COMPILE_TEST_RESOURCES_CONFIG_FOLDER = DELTAKIT_COMPILE_TEST_RESOURCES_FOLDER / "config"
